const continentByCountry = {
    // Europe
    "France": "Europe",
    "Germany": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "Switzerland": "Europe",
    "Belgium": "Europe",
    "Netherlands": "Europe",
    "Portugal": "Europe",
    "Austria": "Europe",
    "Poland": "Europe",
    "Greece": "Europe",
    "Norway": "Europe",
    "Sweden": "Europe",
    "Finland": "Europe",
    "Denmark": "Europe",
    "Ireland": "Europe",
    "United Kingdom": "Europe",
    "Scotland": "Europe",
    "England": "Europe",
    "Wales": "Europe",
    "Ukraine": "Europe",
    "Romania": "Europe",
    "Hungary": "Europe",
    "Czech Republic": "Europe",
    "Slovakia": "Europe",
    "Croatia": "Europe",
    "Serbia": "Europe",
    "Slovenia": "Europe",
    "Bulgaria": "Europe",
    "Albania": "Europe",
    "Estonia": "Europe",
    "Latvia": "Europe",
    "Lithuania": "Europe",
    "Iceland": "Europe",
    "Luxembourg": "Europe",

    // North America
    "Canada": "North America",
    "United States": "North America",
    "Mexico": "North America",
    "Cuba": "North America",
    "Jamaica": "North America",
    "Panama": "North America",
    "Costa Rica": "North America",
    "Guatemala": "North America",

    // South America
    "Brazil": "South America",
    "Argentina": "South America",
    "Chile": "South America",
    "Peru": "South America",
    "Colombia": "South America",
    "Bolivia": "South America",
    "Ecuador": "South America",
    "Uruguay": "South America",
    "Paraguay": "South America",
    "Venezuela": "South America",

    // Asia
    "China": "Asia",
    "Japan": "Asia",
    "South Korea": "Asia",
    "India": "Asia",
    "Thailand": "Asia",
    "Vietnam": "Asia",
    "Cambodia": "Asia",
    "Indonesia": "Asia",
    "Malaysia": "Asia",
    "Philippines": "Asia",
    "Nepal": "Asia",
    "Pakistan": "Asia",
    "Sri Lanka": "Asia",
    "Saudi Arabia": "Asia",
    "United Arab Emirates": "Asia",
    "Qatar": "Asia",
    "Iran": "Asia",
    "Iraq": "Asia",
    "Jordan": "Asia",
    "Israel": "Asia",
    "Turkey": "Asia",
    "Kazakhstan": "Asia",
    "Mongolia": "Asia",

    // Africa
    "Egypt": "Africa",
    "Morocco": "Africa",
    "Algeria": "Africa",
    "Tunisia": "Africa",
    "South Africa": "Africa",
    "Kenya": "Africa",
    "Tanzania": "Africa",
    "Uganda": "Africa",
    "Ethiopia": "Africa",
    "Madagascar": "Africa",
    "Zimbabwe": "Africa",
    "Botswana": "Africa",
    "Namibia": "Africa",
    "Senegal": "Africa",
    "Mali": "Africa",
    "Nigeria": "Africa",
    "Ghana": "Africa",

    // Oceania
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    "Fiji": "Oceania",
    "Papua New Guinea": "Oceania",
    "Samoa": "Oceania",
};
export { continentByCountry }